### ISSUE TITLE
Qt frontend not working on Python 3.8

### ISSUE THREAD

**Issue by FichteFoll** [z411/trackma#467]
With the release of Qt 5.14, which finally supports Python 3.8, the qt frontend doesn't appear to launch. ~~I read on Qt's issue tracker that 3.8.0 has a bug and only 3.8.1 is supported, so this may clean up itself, but I wanted to report it anyway to make sure.~~ Also occurs on 3.8.1.

```
~ ↻ trackma-qt
Trackma-qt v0.8.2
Traceback (most recent call last):
  File "/usr/bin/trackma-qt", line 11, in <module>
    load_entry_point('Trackma==0.8.2', 'gui_scripts', 'trackma-qt')()
  File "/usr/lib/python3.8/site-packages/trackma/ui/qt/__init__.py", line 81, in main
    mainwindow = MainWindow(debug)
  File "/usr/lib/python3.8/site-packages/trackma/ui/qt/mainwindow.py", line 92, in __init__
    self.start(default)
  File "/usr/lib/python3.8/site-packages/trackma/ui/qt/mainwindow.py", line 248, in start
    self.mediatype_actiongroup = QActionGroup(self, exclusive=True)
TypeError: 'exclusive' is an unknown keyword argument
QFileSystemWatcher::removePaths: list is empty
QFileSystemWatcher::removePaths: list is empty
 ?=1
~ ↻ trackma-qt4
Trackma-qt v0.8.2
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2451, in resolve
    return functools.reduce(getattr, self.attrs, module)
AttributeError: module 'trackma.ui.qt.qt4ui' has no attribute 'main'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/trackma-qt4", line 11, in <module>
    load_entry_point('Trackma==0.8.2', 'gui_scripts', 'trackma-qt4')()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2453, in resolve
    raise ImportError(str(exc))
ImportError: module 'trackma.ui.qt.qt4ui' has no attribute 'main'
 ?=1
~ Λ python --version
Python 3.8.0
```

Trackma's version is current `master`, my system is Arch.

**Comment by BanchouBoo** [comment]
Do other UI's work? The 3.8 update broke a lot of installations of python programs, requiring them to be reinstalled, so if you haven't done that yet try that.

**Comment by FichteFoll** [comment]
Yes, the other UIs work fine. I mostly use the CLI, personally.

**Comment by BanchouBoo** [comment]
The qt UI works fine for me on Python 3.8.0 so I'm inclined to believe that the issue is in some way related to the breakage to everything that the update caused. Have you or this person done a fresh install of Trackma?

**Comment by FichteFoll** [comment]
I rebuilt trackma on 2019-11-17, after I updated my system to 3.8. The other person has reinstalled and -built trackma on the day of the report.

**Comment by FichteFoll** [comment]
Since I just saw that Python 3.8.1 is available on Arch repos, I updated that and explcitly rebuilt trackma to no avail.

**Comment by z411** [comment]
Sorry I got a new computer and it's working terribly so I can't test it myself; did by any chance #468 fix this?

**Comment by FichteFoll** [comment]
The changeset looks like it should fix the issue. I don't know how backwards-compatible the change is, however, and haven't tested it.

**Comment by FichteFoll** [comment]
I just checked this again and seems to have solved itself, probably via a qt upstream fix.
